### ISSUE TITLE
does not work on ios, misleading hint on desktop

### ISSUE THREAD

**Issue by r10s** [DeltaZen/Dino#1]
this does not work on ios for me. tapping the screen does not have any effect.

on desktop/macos, the hint "press space" works only after clicking one time to the window - seems as if  the webxdc-window does not have the focus, ~~but that is probably a general desktop issue~~ EDIT: probably not, see below

**Comment by r10s** [comment]
> but that is probably a general desktop ossue

it seems not to be a general desktop issue - eg. in the checklist app, the just opened xdc has the "add item" input focused and you can type directly without the need to click first.

so, the "press space to start" is misleading as it does not work before at least one click into the window - sure, this is a minor issue, i assume quite some apps have similar issues, however, it may give a hint for fixing the ios issue (both looks similar stale before, maybe it is just a missing focus)

**Comment by adbenitez** [comment]
the issue with keyboard event in desktop was solved in https://github.com/DeltaZen/Dino/commit/142981cb316f8391aef2bd99746141a4af3af11f

as of iOS, I would need your help to give more feedback there, download this version with eruda dev tools included and report back with the screenshot of what you see in the dev console:
https://temp.sh/cMhdb/Dino-2046976734.xdc

**Comment by hpk42** [comment]
FWIW there is an iphone at bb33 which might be useful for testing.

**Comment by r10s** [comment]
yes, it is better if you pick up the bb33 phone

however, i gave the xdc a shot: this is what i got direct after start - not sure if that is related or how i can expand th me info (obvious things do not work) 

<img width=320 src=https://github.com/DeltaZen/Dino/assets/9800740/063c0922-8bf0-4ab2-a456-b056535d7548>

**Comment by adbenitez** [comment]
fixed in e6816bcb37b0d46105cc41cb4d812db573572bfd
